version: 2.1
 
orbs:
  android: circleci/android@2.3.0
 
jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Create local.properties
          command: |
             echo "sdk.dir=$ANDROID_HOME" > local.properties
             echo "NEWS_API_KEY=$NEWS_API_KEY" >> local.properties
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - .gradle/configuration-cache
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file